# Basic
title: Hentin Young
subtitle: 我的页面
description: Welcome
# 头像里面的标题
avatarTitle: Baconhentin
# 头像里面的描述
avatarDesc: 杂享
url: "https://zajiaht.com"

# Comment
#comment:
    #disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    weibo: yht7311
    #github: baconhentin
    # twitter:
    #mail: yht1632662248@gmail.com

# 百度统计
# 使用博客模板请去掉或者更换 id
baidu:
    id: 3132f87c743b905c1a3de618fcd01ad7

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
    #id:
    #host: auto


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 我的主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}
    - {title: 标签, description: tags, url: '/tags'}
    - {title: 了解我, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
